@startuml

package "EIS" {
    [Claims Integration] as ci #lightgreen
    [Party] as party #lightblue
    [Claims] as claims #lightblue
    [Policy] as policy #lightblue
    [Customer] as crm #lightblue
    [Billing] as billing #lightblue

crm - policy
crm -- party
party - claims
policy - claims
crm - claims
policy - billing
claims - ci

}

package "External Claims System" {
    interface SOAP #red
    [External Claims] as extcl #red

    SOAP - extcl
    ci <--> SOAP
}

legend
|= |= Type |
|<back:#red>   </back>| Third Party |
|<back:#lightgreen>   </back>| Integration |
|<back:#lightblue>   </back>| EIS |
endlegend

@enduml